# Generated by Django 3.2.13 on 2022-06-29 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='DiskType',
            fields=[
                ('commoninfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server.commoninfo')),
            ],
            bases=('server.commoninfo',),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('commoninfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server.commoninfo')),
            ],
            bases=('server.commoninfo',),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('commoninfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server.commoninfo')),
            ],
            bases=('server.commoninfo',),
        ),
        migrations.CreateModel(
            name='ServerType',
            fields=[
                ('commoninfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server.commoninfo')),
            ],
            bases=('server.commoninfo',),
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('cpu', models.CharField(max_length=63)),
                ('ram', models.CharField(choices=[('gb', 'GB'), ('tb', 'TB')], default='gb', max_length=3)),
                ('ip_address', models.CharField(max_length=63)),
                ('username', models.CharField(max_length=63)),
                ('password', models.CharField(max_length=63)),
                ('public_ip', models.CharField(max_length=63)),
                ('private_ip', models.CharField(max_length=63)),
                ('remarks', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.owner')),
                ('disk_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.disktype')),
                ('server_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.location')),
                ('server_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.servertype')),
            ],
        ),
    ]
